"""
Production-Grade Module Manifest: Dashboard
Generated by: aq add module Dashboard

Defines complete module configuration including:
- Services with DI scopes and lifecycle
- Controllers with routing
- Middleware with scoping and priority
- Sessions with policies
- Error handling with fault domains
- Feature flags with conditional activation
"""

from datetime import timedelta
from aquilia import AppManifest
from aquilia.manifest import (
    FaultHandlingConfig, FaultHandlerConfig,
    MiddlewareConfig,
    SessionConfig,
    LifecycleConfig,
    FeatureConfig,
)


# Production-grade manifest with complete configuration
manifest = AppManifest(
    # Identity
    name="Dashboard",
    version="0.1.0",
    description="Dashboard module",
    author="team@company.com",
    tags=["Dashboard", "core"],

    # Services with detailed DI configuration
    services=[
        "modules.Dashboard.services:DashboardService",
    ],

    # Controllers with routing
    controllers=[
        "modules.Dashboard.controllers:DashboardController",
    ],

    # Middleware configuration
    middleware=[
        # Example middleware (uncomment to add):
        # MiddlewareConfig(
        #     class_path="modules.Dashboard.middleware:AuthMiddleware",
        #     scope="app",
        #     priority=10,
        #     config={},
        # ),
    ],

    # Routing configuration
    route_prefix="/Dashboard",
    base_path="modules.Dashboard",

    # Error handling with fault domains
    faults=FaultHandlingConfig(
        default_domain="DASHBOARD",
        strategy="propagate",
        handlers=[
            # Example fault handler (uncomment to add):
            # FaultHandlerConfig(
            #     domain="DASHBOARD:NOT_FOUND",
            #     handler_path="modules.Dashboard.handlers:handle_not_found",
            # ),
        ],
    ),

    # Session management
    sessions=[
        # Example session (uncomment to add):
        # SessionConfig(
        #     name="Dashboard_session",
        #     enabled=True,
        #     ttl=timedelta(days=7),
        #     idle_timeout=timedelta(hours=1),
        #     transport="cookie",
        #     store="memory",
        # ),
    ],

    # Feature flags
    features=[
        # Example feature (uncomment to add):
        # FeatureConfig(
        #     name="advanced_search",
        #     enabled=False,
        # ),
    ],

    # Dependencies on other modules
    depends_on=[],
)


__all__ = ["manifest"]