"""
Module Manifest: modeboom
Generated by: aq add module modeboom

This file defines the module configuration using Python.
"""

from aquilia import Module


# Module configuration
manifest = Module(
    name="modeboom",
    version="0.1.0",
    description="Modeboom module",
).auto_discover(True)

# Routing configuration
manifest.route_prefix = "/modeboom"

# Fault handling configuration
manifest.fault_domain = "MODEBOOM"
manifest.fault_strategy = "propagate"

# Dependencies
manifest.dependencies = []

# DI providers (auto-discovered from services.py)
# Or explicitly declare:
# manifest.register_providers({"class": "MyService", "scope": "singleton"})

# Routes (auto-discovered from controllers.py)
# Or explicitly declare:
# manifest.register_controllers("module.controllers:MyController")
# manifest.register_routes({"path": "/foo", "handler": "bar"})


# Export for module loader
__all__ = ["manifest"]