"""
Mymod Module.

Generated by: aq add module mymod
"""

from .controllers import *
from .test_routes import *
from .services import *
from .faults import *

__module_name__ = "mymod"
__version__ = "0.1.0"