"""
Production-Grade Module Manifest: myappmod
Generated by: aq add module myappmod

Defines complete module configuration including:
- Services with DI scopes and lifecycle
- Controllers with routing
- Middleware with scoping and priority
- Sessions with policies
- Error handling with fault domains
- Feature flags with conditional activation
"""

from datetime import timedelta
from aquilia import AppManifest
from aquilia.manifest import (
    FaultHandlingConfig, FaultHandlerConfig,
    MiddlewareConfig,
    ServiceConfig,
    SessionConfig,
    LifecycleConfig,
    FeatureConfig,
)


# Production-grade manifest with complete configuration
manifest = AppManifest(
    # Identity
    name="myappmod",
    version="0.1.0",
    description="Myappmod module",
    author="team@company.com",
    tags=["myappmod", "core"],

    # Services with detailed DI configuration
    services=[
        # Bind IUserRepository interface to MemoryUserRepository implementation
        ServiceConfig(
            class_path="modules.myappmod.advanced_di:MemoryUserRepository",
            aliases=["modules.myappmod.advanced_di:IUserRepository"],
            scope="singleton",
        ),
        "modules.myappmod.advanced_di:SqlUserRepository",
        # Factory for DB Config
        ServiceConfig(
            class_path="typing.Dict", # Token is determined by factory name "db_config"
            factory="modules.myappmod.advanced_di:create_db_config",
            scope="singleton",
        ),
        "modules.myappmod.services:MyappmodService",
        "modules.myappmod.services_ext:AuditLogger",
        "modules.myappmod.services_ext:ExpensiveService",
        "modules.myappmod.services_ext:LazyProcessor",
    ],
    # Controllers with routing
    controllers=[
        "modules.myappmod.advanced_di:AdvancedUserController",
        "modules.myappmod.controllers:AdvancedFeaturesController",
        "modules.myappmod.controllers:MyappmodController",
        "modules.myappmod.sessioncontrol.sessions:SessionController",
    ],
    # Middleware configuration
    middleware=[
        MiddlewareConfig(
            class_path="modules.myappmod.middleware:AuthSimulationMiddleware",
            scope="app",
            priority=10,
            config={},
        ),
    ],

    # Routing configuration
    route_prefix="/myappmod",
    base_path="modules.myappmod",

    # Error handling with fault domains
    faults=FaultHandlingConfig(
        default_domain="MYAPPMOD",
        strategy="propagate",
        handlers=[
            # Example fault handler (uncomment to add):
            # FaultHandlerConfig(
            #     domain="MYAPPMOD:NOT_FOUND",
            #     handler_path="modules.myappmod.handlers:handle_not_found",
            # ),
        ],
    ),

    # Session management
    sessions=[
        # Example session (uncomment to add):
        # SessionConfig(
        #     name="myappmod_session",
        #     enabled=True,
        #     ttl=timedelta(days=7),
        #     idle_timeout=timedelta(hours=1),
        #     transport="cookie",
        #     store="memory",
        # ),
    ],

    # Feature flags
    features=[
        # Example feature (uncomment to add):
        # FeatureConfig(
        #     name="advanced_search",
        #     enabled=False,
        # ),
    ],

    # Dependencies on other modules
    depends_on=[],
)


__all__ = ["manifest"]