"""
Production-Grade Module Manifest: dummy
Generated by: aq add module dummy

Defines complete module configuration including:
- Services with DI scopes and lifecycle
- Controllers with routing
- Middleware with scoping and priority
- Sessions with policies
- Error handling with fault domains
- Feature flags with conditional activation
"""

from datetime import timedelta
from aquilia import AppManifest
from aquilia.manifest import (
    FaultHandlingConfig, FaultHandlerConfig,
    MiddlewareConfig,
    SessionConfig,
    LifecycleConfig,
    FeatureConfig,
)


# Production-grade manifest with complete configuration
manifest = AppManifest(
    # Identity
    name="dummy",
    version="0.1.0",
    description="Dummy module",
    author="team@company.com",
    tags=["dummy", "core"],

    # Services with detailed DI configuration
    services=[
        "modules.dummy.services:DummyService",
    ],

    # Controllers with routing
    controllers=[
        "modules.dummy.controllers:DummyController",
    ],

    # Middleware configuration
    middleware=[
        # Example middleware (uncomment to add):
        # MiddlewareConfig(
        #     class_path="modules.dummy.middleware:AuthMiddleware",
        #     scope="app",
        #     priority=10,
        #     config={},
        # ),
    ],

    # Routing configuration
    route_prefix="/dummy",
    base_path="modules.dummy",

    # Error handling with fault domains
    faults=FaultHandlingConfig(
        default_domain="DUMMY",
        strategy="propagate",
        handlers=[
            # Example fault handler (uncomment to add):
            # FaultHandlerConfig(
            #     domain="DUMMY:NOT_FOUND",
            #     handler_path="modules.dummy.handlers:handle_not_found",
            # ),
        ],
    ),

    # Session management
    sessions=[
        # Example session (uncomment to add):
        # SessionConfig(
        #     name="dummy_session",
        #     enabled=True,
        #     ttl=timedelta(days=7),
        #     idle_timeout=timedelta(hours=1),
        #     transport="cookie",
        #     store="memory",
        # ),
    ],

    # Feature flags
    features=[
        # Example feature (uncomment to add):
        # FeatureConfig(
        #     name="advanced_search",
        #     enabled=False,
        # ),
    ],

    # Dependencies on other modules
    depends_on=[],
)


__all__ = ["manifest"]