"""Workspace generator."""

from pathlib import Path
from typing import Optional
import textwrap


class WorkspaceGenerator:
    """Generate Aquilia workspace structure."""
    
    def __init__(
        self,
        name: str,
        path: Path,
        minimal: bool = False,
        template: Optional[str] = None,
    ):
        self.name = name
        self.path = path
        self.minimal = minimal
        self.template = template
    
    def generate(self) -> None:
        """Generate workspace structure."""
        self.path.mkdir(parents=True, exist_ok=True)
        
        # Create directory structure
        self._create_directories()
        
        # Create manifest files
        self._create_workspace_manifest()
        self._create_config_files()
        
        # Create additional files
        if not self.minimal:
            self._create_gitignore()
            self._create_readme()
    
    def _create_directories(self) -> None:
        """Create workspace directories."""
        dirs = ['modules', 'config']
        
        if not self.minimal:
            dirs.extend(['artifacts', 'runtime'])
        
        for dir_name in dirs:
            (self.path / dir_name).mkdir(exist_ok=True)
    
    def _create_workspace_manifest(self) -> None:
        """Create aquilia.py configuration (Python-based)."""
        content = textwrap.dedent(f'''\
            """
            Aquilia Workspace Configuration
            Generated by: aq init workspace {self.name}
            
            This file defines the WORKSPACE STRUCTURE (modules, integrations).
            Runtime settings (host, port, workers) come from config/dev.yaml or config/prod.yaml.
            
            Separation of concerns:
            - aquilia.py = Workspace structure (version-controlled, shared)
            - config/*.yaml = Runtime settings (environment-specific, potentially secret)
            """
            
            from aquilia import Workspace, Module, Integration
            from aquilia.sessions import SessionPolicy, MemoryStore, TransportPolicy
            from datetime import timedelta
            
            
            # Define workspace structure (NOT runtime config)
            workspace = (
                Workspace("{self.name}", version="0.1.0", description="Aquilia workspace")
                # Runtime config (host, port, mode, workers) comes from config/*.yaml
                # This keeps workspace definition clean and environment-agnostic
                
                # Add modules here:
                # .module(Module("users").route_prefix("/users"))
                
                # Integrations
                .integrate(Integration.di(auto_wire=True))
                .integrate(Integration.registry())
                .integrate(Integration.routing(strict_matching=True))
                .integrate(Integration.fault_handling(default_strategy="propagate"))
                .integrate(Integration.patterns())
                
                # Optional: Enable sessions
                # .integrate(Integration.sessions(
                #     policy=SessionPolicy(
                #         name="user_default",
                #         ttl=timedelta(days=7),
                #         idle_timeout=timedelta(minutes=30),
                #         transport=TransportPolicy(
                #             adapter="cookie",
                #             cookie_name="{self.name}_session",
                #             cookie_httponly=True,
                #             cookie_secure=True,
                #         ),
                #     ),
                #     store=MemoryStore(max_sessions=1000),
                # ))
            )
            
            
            # Export for CLI/server
            __all__ = ["workspace"]
        ''').strip()
        
        (self.path / 'workspace.py').write_text(content)
    
    def _create_config_files(self) -> None:
        """Create environment configuration files."""
        # base.yaml - Shared defaults
        base_config = textwrap.dedent("""
            # Base Configuration
            #
            # Shared configuration across ALL environments.
            # Environment-specific files (dev.yaml, prod.yaml) override these values.
            
            runtime:
              # Defaults (overridden by environment configs)
              mode: dev
              host: 127.0.0.1
              port: 8000
              reload: false
              workers: 1
            
            logging:
              level: INFO
              format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
            
            # Application defaults
            debug: false
        """).strip()
        
        (self.path / 'config' / 'base.yaml').write_text(base_config)
        
        # dev.yaml - Development environment
        dev_config = textwrap.dedent("""
            # Development Environment Configuration
            # 
            # This file contains RUNTIME SETTINGS for development.
            # Workspace structure (modules, integrations) is defined in aquilia.py.
            #
            # Merge strategy:
            #   1. Load workspace structure from aquilia.py
            #   2. Load base config from config/base.yaml
            #   3. Merge environment config (this file)
            #   4. Apply environment variables (AQ_* prefix)
            
            runtime:
              mode: dev
              host: 127.0.0.1
              port: 8000
              reload: true
              workers: 1
            
            logging:
              level: DEBUG
              format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
            
            # Development-specific settings
            debug: true
        """).strip()
        
        (self.path / 'config' / 'dev.yaml').write_text(dev_config)
        
        # prod.yaml - Production environment
        prod_config = textwrap.dedent("""
            # Production Environment Configuration
            #
            # This file contains RUNTIME SETTINGS for production.
            # Workspace structure (modules, integrations) is defined in aquilia.py.
            
            runtime:
              mode: prod
              host: 0.0.0.0
              port: 8000
              reload: false
              workers: 4
            
            logging:
              level: WARNING
              format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
            
            # Production-specific settings
            debug: false
        """).strip()
        
        (self.path / 'config' / 'prod.yaml').write_text(prod_config)
    
    def _create_gitignore(self) -> None:
        """Create .gitignore file."""
        content = textwrap.dedent("""
            # Python
            __pycache__/
            *.py[cod]
            *$py.class
            *.so
            .Python
            env/
            venv/
            ENV/
            
            # Aquilia
            artifacts/
            runtime/
            *.crous
            
            # IDE
            .vscode/
            .idea/
            *.swp
            *.swo
            
            # OS
            .DS_Store
            Thumbs.db
        """).strip()
        
        (self.path / '.gitignore').write_text(content)
    
    def _create_readme(self) -> None:
        """Create README.md file."""
        content = textwrap.dedent(f"""
            # {self.name}
            
            Aquilia workspace generated with `aq init workspace {self.name}`.
            
            ## Structure
            
            ```
            {self.name}/
              aquilia.py          # Workspace configuration (Python)
              modules/            # Application modules
              config/             # Environment-specific configs
                base.yaml        # Base config
                dev.yaml         # Development config
                prod.yaml        # Production config
              artifacts/          # Compiled artifacts
              runtime/            # Runtime state
            ```
            
            ## Configuration Architecture
            
            Aquilia uses a **professional separation of concerns**:
            
            - **`aquilia.py`** - Workspace structure (modules, integrations)
              - Version-controlled and shared across team
              - Environment-agnostic
              - Type-safe Python API
            
            - **`config/*.yaml`** - Runtime settings (host, port, workers)
              - Environment-specific (dev, prod, staging)
              - Can contain secrets (not committed)
              - Merged in order: base → environment → env vars
            
            ## Getting Started
            
            ### Add a module
            
            ```bash
            aq add module users
            ```
            
            This will update `aquilia.py`:
            
            ```python
            workspace = (
                Workspace("{self.name}", version="0.1.0")
                .module(Module("users").route_prefix("/users"))
                ...
            )
            ```
            
            ### Run development server
            
            ```bash
            aq run
            ```
            
            This loads: `aquilia.py` + `config/base.yaml` + `config/dev.yaml`
            
            ### Run production server
            
            ```bash
            aq run --mode=prod
            ```
            
            This loads: `aquilia.py` + `config/base.yaml` + `config/prod.yaml`
            
            ## Session Management
            
            Enable sessions with unique Aquilia syntax in `aquilia.py`:
            
            ```python
            workspace = (
                Workspace("{self.name}", version="0.1.0")
                .integrate(Integration.sessions(
                    policy=SessionPolicy(ttl=timedelta(days=7)),
                    store=MemoryStore(max_sessions=1000),
                ))
            )
            ```
            
            Then use in controllers:
            
            ```python
            from aquilia import session, authenticated, stateful
            
            @GET("/profile")
            @authenticated
            async def profile(ctx, user: SessionPrincipal):
                return {{"user_id": user.id}}
            
            @POST("/cart")
            @stateful
            async def cart(ctx, state: SessionState):
                state._data['items'].append(item)
            ```
            
            ## Commands
            
            - `aq add module <name>` - Add new module
            - `aq validate` - Validate configuration
            - `aq compile` - Compile to artifacts
            - `aq run` - Development server
            - `aq run --mode=prod` - Production server
            - `aq serve` - Production server (frozen artifacts)
            - `aq freeze` - Generate immutable artifacts
            - `aq inspect routes` - Inspect compiled routes
            - `aq sessions list` - List active sessions
            - `aq doctor` - Diagnose issues
            
            ## Documentation
            
            See Aquilia documentation for complete guides.
        """).strip()
        
        (self.path / 'README.md').write_text(content)
