"""Workspace generator."""

from pathlib import Path
from typing import Optional
import textwrap


class WorkspaceGenerator:
    """Generate Aquilia workspace structure."""
    
    def __init__(
        self,
        name: str,
        path: Path,
        minimal: bool = False,
        template: Optional[str] = None,
    ):
        self.name = name
        self.path = path
        self.minimal = minimal
        self.template = template
    
    def generate(self) -> None:
        """Generate workspace structure."""
        self.path.mkdir(parents=True, exist_ok=True)
        
        # Create directory structure
        self._create_directories()
        
        # Create manifest files
        self._create_workspace_manifest()
        self._create_config_files()
        
        # Create additional files
        if not self.minimal:
            self._create_gitignore()
            self._create_readme()
    
    def _create_directories(self) -> None:
        """Create workspace directories."""
        dirs = ['modules', 'config']
        
        if not self.minimal:
            dirs.extend(['artifacts', 'runtime'])
        
        for dir_name in dirs:
            (self.path / dir_name).mkdir(exist_ok=True)
    
    def _create_workspace_manifest(self) -> None:
        """Create aquilia.aq manifest."""
        content = textwrap.dedent(f"""
            # Aquilia Workspace Manifest
            # Generated by: aq init workspace {self.name}
            
            workspace:
              name: {self.name}
              version: "0.1.0"
              description: "Aquilia workspace"
            
            runtime:
              # Default runtime configuration
              mode: dev
              host: 127.0.0.1
              port: 8000
              workers: 1
            
            modules:
              # Modules will be registered here via `aq add module <name>`
              []
              # Example:
              # - name: users
              #   fault_domain: USERS
              #   route_prefix: /users
            
            integrations:
              # Subsystem integrations
              registry:
                enabled: true
              
              dependency_injection:
                enabled: true
                auto_wire: true
              
              routing:
                enabled: true
                strict_matching: true
              
              fault_handling:
                enabled: true
                default_strategy: propagate
              
              patterns:
                enabled: true
        """).strip()
        
        (self.path / 'aquilia.aq').write_text(content)
    
    def _create_config_files(self) -> None:
        """Create configuration files."""
        # base.aq
        base_config = textwrap.dedent("""
            # Base Configuration
            # Shared across all environments
            
            app:
              name: "Aquilia Application"
              debug: false
            
            server:
              timeout: 30
              max_connections: 1000
            
            logging:
              level: INFO
              format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        """).strip()
        
        (self.path / 'config' / 'base.aq').write_text(base_config)
        
        # dev.aq
        dev_config = textwrap.dedent("""
            # Development Configuration
            
            app:
              debug: true
            
            server:
              host: 127.0.0.1
              port: 8000
              reload: true
            
            logging:
              level: DEBUG
        """).strip()
        
        (self.path / 'config' / 'dev.aq').write_text(dev_config)
        
        # prod.aq
        prod_config = textwrap.dedent("""
            # Production Configuration
            
            server:
              host: 0.0.0.0
              port: 8000
              workers: 4
              reload: false
            
            logging:
              level: WARNING
        """).strip()
        
        (self.path / 'config' / 'prod.aq').write_text(prod_config)
    
    def _create_gitignore(self) -> None:
        """Create .gitignore file."""
        content = textwrap.dedent("""
            # Python
            __pycache__/
            *.py[cod]
            *$py.class
            *.so
            .Python
            env/
            venv/
            ENV/
            
            # Aquilia
            artifacts/
            runtime/
            *.crous
            
            # IDE
            .vscode/
            .idea/
            *.swp
            *.swo
            
            # OS
            .DS_Store
            Thumbs.db
        """).strip()
        
        (self.path / '.gitignore').write_text(content)
    
    def _create_readme(self) -> None:
        """Create README.md file."""
        content = textwrap.dedent(f"""
            # {self.name}
            
            Aquilia workspace generated with `aq init workspace {self.name}`.
            
            ## Structure
            
            ```
            {self.name}/
              aquilia.aq          # Workspace manifest
              modules/            # Application modules
              config/             # Configuration files
                base.aq          # Base config
                dev.aq           # Development config
                prod.aq          # Production config
              artifacts/          # Compiled artifacts
              runtime/            # Runtime state
            ```
            
            ## Getting Started
            
            ### Add a module
            
            ```bash
            aq add module users
            ```
            
            ### Validate manifests
            
            ```bash
            aq validate
            ```
            
            ### Compile artifacts
            
            ```bash
            aq compile
            ```
            
            ### Run development server
            
            ```bash
            aq run
            ```
            
            ## Commands
            
            - `aq add module <name>` - Add new module
            - `aq validate` - Validate manifests
            - `aq compile` - Compile to artifacts
            - `aq run` - Development server
            - `aq serve` - Production server
            - `aq freeze` - Generate immutable artifacts
            - `aq inspect routes` - Inspect compiled routes
            - `aq doctor` - Diagnose issues
            
            ## Documentation
            
            See `docs/AQUILATE_DESIGN.md` for complete design documentation.
        """).strip()
        
        (self.path / 'README.md').write_text(content)
