"""
Aquilia Workspace Configuration - Production Grade
Generated by: aq init workspace myapp

This file defines the WORKSPACE STRUCTURE (modules, integrations).
It is:
- Environment-agnostic
- Version-controlled and shared across team
- Type-safe with full IDE support
- Observable via introspection

Runtime settings (host, port, workers) come from config/dev.yaml or config/prod.yaml.

Separation of concerns:
- aquilia.py (THIS FILE) = Workspace structure (modules, integrations)
- config/base.yaml = Shared configuration defaults
- config/{mode}.yaml = Environment-specific runtime settings (dev, prod)
- Environment variables = Override mechanism for secrets and env-specific values
"""

from aquilia import Workspace, Module, Integration
from datetime import timedelta
from aquilia.sessions import SessionPolicy

# Define workspace structure
workspace = (
    Workspace(
        name="myapp",
        version="0.1.0",
        description="Aquilia workspace",
    )

    # Add modules here with explicit configuration:
    #).depends_on("core"))
    #).depends_on("auth", "core"))

    .module(Module("mymodule", version="0.1.0", description="Mymodule module")
        .route_prefix("/mymodule")
        .tags("mymodule", "core")
        .register_controllers(
            "modules.mymodule.controllers:MymoduleController"
        )
        .register_services(
            "modules.mymodule.services:MymoduleService"
        ))

    .module(Module("mymodule", version="0.1.0", description="Mymodule module")
        .route_prefix("/mymodule")
        .tags("mymodule", "core")
        .register_controllers(
            "modules.mymodule.controllers:MymoduleController"
        )
        .register_services(
            "modules.mymodule.services:MymoduleService"
        ))

    .module(Module("mymodule", version="0.1.0", description="Mymodule module")
        .route_prefix("/mymodule")
        .tags("mymodule", "core")
        .register_controllers(
            "modules.mymodule.controllers:MymoduleController"
        )
        .register_services(
            "modules.mymodule.services:MymoduleService"
        ))

    .module(Module("mymodule", version="0.1.0", description="Mymodule module")
        .route_prefix("/mymodule")
        .tags("mymodule", "core")
        .register_controllers(
            "modules.mymodule.controllers:MymoduleController"
        )
        .register_services(
            "modules.mymodule.services:MymoduleService"
        ))

    # Integrations - Configure core systems
    .integrate(Integration.di(auto_wire=True, manifest_validation=True))
    .integrate(Integration.registry(
        mode="auto",  # "dev", "prod", "auto" (env-based)
        fingerprint_verification=True,
    ))
    .integrate(Integration.routing(
        strict_matching=True,
        version_support=True,
        compression=True,
    ))
    .integrate(Integration.fault_handling(
        default_strategy="propagate",
        metrics_enabled=True,
    ))
    .integrate(Integration.patterns())

    # Sessions - Configure session management with unique Aquilia syntax
    .sessions(
        policies=[
            # Web application session with unique Aquilia fluent builder
            (SessionPolicy
             .for_web_users()
             .lasting(days=7)
             .idle_timeout(hours=2)
             .rotating_on_auth()
             .web_defaults()
             .build()),
        ],
    )

    # Security - Enable/disable security features
    .security(
        cors_enabled=False,
        csrf_protection=False,
        helmet_enabled=True,
        rate_limiting=True,
    )

    # Telemetry - Enable observability
    .telemetry(
        tracing_enabled=False,
        metrics_enabled=True,
        logging_enabled=True,
    )
)

# Export for CLI/server
__all__ = ["workspace"]