"""
Aquilia Workspace Configuration - Full Showcase
Generated by: aq init workspace myapp

This workspace demonstrates EVERY major Aquilia feature:
- Modules: blogs, users, products, chat, tasks, pages, sessions
- Integrations: DI, registry, routing, faults, patterns, templates
- Sessions: policies, stores, transports
- Security: CORS, CSRF, helmet, rate limiting
- Telemetry: tracing, metrics, logging

Separation of concerns:
- workspace.py (THIS FILE) = Workspace structure (modules, integrations)
- config/base.yaml = Shared configuration defaults
- config/{mode}.yaml = Environment-specific runtime settings (dev, prod)
- Environment variables = Override mechanism for secrets and env-specific values
"""

from aquilia import Workspace, Module, Integration
from datetime import timedelta
from aquilia.sessions import SessionPolicy, PersistencePolicy, ConcurrencyPolicy, TransportPolicy

# Define workspace structure
workspace = (
    Workspace(
        name="myapp",
        version="0.2.0",
        description="Aquilia full-feature showcase workspace",
    )

    # ---- Modules ---------------------------------------------------------

    .module(Module("blogs", version="0.1.0", description="Blogs module")
        .route_prefix("/blogs")
        .tags("blogs", "core")
        .register_controllers(
            "modules.blogs.controllers:BlogsController"
        )
        .register_services(
            "modules.blogs.services:BlogsService"
        ))

    .module(Module("tasks", version="0.1.0", description="Task management with structured faults, validation, and state machines")
        .route_prefix("/tasks")
        .tags("tasks", "faults", "effects")
        .register_controllers(
            "modules.tasks.controllers:TasksController"
        )
        .register_services(
            "modules.tasks.services:TaskService"
        ))

    .module(Module("products", version="0.1.0", description="Product catalog with pure Python models, reviews, and stock management")
        .route_prefix("/products")
        .tags("products", "catalog", "models")
        .register_controllers(
            "modules.products.controllers:ProductsController"
        )
        .register_services(
            "modules.products.services:ProductRepository",
            "modules.products.services:ProductService"
        ))

    .module(Module("chat", version="0.1.0", description="Real-time chat with WebSockets, rooms, presence, and message history")
        .route_prefix("/chat")
        .tags("chat", "websocket", "realtime")
        .register_controllers(
            "modules.chat.controllers:ChatController"
        )
        .register_services(
            "modules.chat.services:ChatRoomService",
            "modules.chat.services:MessageService",
            "modules.chat.services:PresenceService"
        )
        .register_sockets(
            "modules.chat.sockets:ChatSocket",
            "modules.chat.sockets:NotificationSocket"
        ))

    .module(Module("sessions", version="0.1.0", description="Session management showcase: cart, preferences, wizard, and lifecycle")
        .route_prefix("/sessions")
        .tags("sessions", "cart", "preferences", "wizard")
        .register_controllers(
            "modules.sessions.controllers:SessionsController"
        )
        .register_services(
            "modules.sessions.services:CartService",
            "modules.sessions.services:PreferencesService"
        ))

    .module(Module("users", version="0.1.0", description="User management with auth, sessions, and DI")
        .route_prefix("/users")
        .tags("users", "auth", "core")
        .register_controllers(
            "modules.users.controllers:UsersController"
        )
        .register_services(
            "modules.users.services:UserRepository",
            "modules.users.services:TokenService",
            "modules.users.services:UserService"
        ))

    .module(Module("pages", version="0.1.0", description="HTML pages with templates, navigation, and lifecycle hooks")
        .route_prefix("/pages")
        .tags("pages", "templates", "frontend")
        .register_controllers(
            "modules.pages.controllers:PagesController"
        )
        .register_services(
            "modules.pages.services:NavigationService",
            "modules.pages.services:PageContentService"
        ))

    # ---- Integrations ----------------------------------------------------

    # DI - Automatic constructor injection with manifest validation
    .integrate(Integration.di(auto_wire=True, manifest_validation=True))

    # Registry - Module registry with fingerprint verification
    .integrate(Integration.registry(
        mode="auto",
        fingerprint_verification=True,
    ))

    # Routing - Pattern-based URL matching with compression
    .integrate(Integration.routing(
        strict_matching=True,
        version_support=True,
        compression=True,
    ))

    # Faults - Structured error handling with metrics
    .integrate(Integration.fault_handling(
        default_strategy="propagate",
        metrics_enabled=True,
    ))

    # Patterns - EBNF-based URL pattern compiler
    .integrate(Integration.patterns())

    # OpenAPI - Interactive API documentation
    .integrate(Integration.openapi(
        title="MyApp API",
        version="1.0.0",
        description=(
            "Production API for the MyApp workspace.\n\n"
            "Built with **Aquilia** — a manifest-driven async Python web framework."
        ),
        contact_name="MyApp Team",
        license_name="MIT",
        docs_path="/docs",
        openapi_json_path="/openapi.json",
        redoc_path="/redoc",
        detect_security=True,
        infer_request_body=True,
        infer_responses=True,
    ))

    # Templates - Jinja2 with module scanning and sandboxing
    .integrate(
        Integration.templates
        .source("templates")
        .scan_modules()
        .cached("memory")
        .secure()
    )

    # Static Files - Serve CSS, JS, images from workspace root
    .integrate(Integration.static_files(
        directories={
            "/static": "static",
        },
        cache_max_age=86400,
        etag=True,
        memory_cache=True,
    ))

    # ---- Sessions --------------------------------------------------------
    .sessions(
        policies=[
            SessionPolicy(
                name="default",
                ttl=timedelta(days=7),
                idle_timeout=timedelta(hours=1),
                rotate_on_privilege_change=True,
                persistence=PersistencePolicy(
                    enabled=True,
                    store_name="memory",
                    write_through=True,
                ),
                concurrency=ConcurrencyPolicy(
                    max_sessions_per_principal=5,
                    behavior_on_limit="evict_oldest",
                ),
                transport=TransportPolicy(
                    adapter="cookie",
                    cookie_httponly=True,
                    cookie_secure=False,
                    cookie_samesite="lax",
                ),
                scope="user",
            ),
        ],
    )

    # ---- Security --------------------------------------------------------
    .security(
        cors_enabled=False,
        csrf_protection=False,
        helmet_enabled=True,
        rate_limiting=True,
    )

    # ---- Telemetry -------------------------------------------------------
    .telemetry(
        tracing_enabled=False,
        metrics_enabled=True,
        logging_enabled=True,
    )
)

# Export for CLI/server
__all__ = ["workspace"]
