"""
Aquilia Workspace Configuration
Generated by: aq init workspace myapp

This file defines the WORKSPACE STRUCTURE (modules, integrations).
Runtime settings (host, port, workers) come from config/dev.yaml or config/prod.yaml.

Separation of concerns:
- aquilia.py = Workspace structure (version-controlled, shared)
- config/*.yaml = Runtime settings (environment-specific, potentially secret)
"""

from aquilia import Workspace, Module, Integration
from aquilia.sessions import SessionPolicy, MemoryStore, TransportPolicy
from datetime import timedelta


# Define workspace structure (NOT runtime config)
workspace = (
    Workspace("myapp", version="0.1.0", description="Aquilia workspace")
    # Runtime config (host, port, mode, workers) comes from config/*.yaml
    # This keeps workspace definition clean and environment-agnostic

    # Add modules here:
    .module(Module("modeboom").route_prefix("/modeboom"))
    # .module(Module("users").route_prefix("/users"))

    # Integrations
    .integrate(Integration.di(auto_wire=True))
    .integrate(Integration.registry())
    .integrate(Integration.routing(strict_matching=True))
    .integrate(Integration.fault_handling(default_strategy="propagate"))
    .integrate(Integration.patterns())

    # Optional: Enable sessions
    # .integrate(Integration.sessions(
    #     policy=SessionPolicy(
    #         name="user_default",
    #         ttl=timedelta(days=7),
    #         idle_timeout=timedelta(minutes=30),
    #         transport=TransportPolicy(
    #             adapter="cookie",
    #             cookie_name="myapp_session",
    #             cookie_httponly=True,
    #             cookie_secure=True,
    #         ),
    #     ),
    #     store=MemoryStore(max_sessions=1000),
    # ))
)


# Export for CLI/server
__all__ = ["workspace"]